trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  name: Restore
  inputs:
    command: 'restore'
    projects: '*/**/*.csproj'
    configuration: Release

- task: DotNetCoreCLI@2
  name: Build
  inputs:
    command: 'build'
    projects: '*/**/*.csproj'
    configuration: Release

- task: DotNetCoreCLI@2
  name: Test
  inputs:
    command: 'test'
    projects: '*/**/*test*.csproj'
    configuration: Release
